### PR TITLE
Add 'Admin' superuser, and 'BlockedUser' user

### LINKED ISSUE #40: Edit User's test data
* Add 'Admin' superuser (instead of Lior).
* Add "BlockedUser" user who is blocked.

These additions are meant to clarify the user's purpose.

### PR DESCRIPTION
**Pull request by liornoy**
Change 'Lior' to a user instead of a superuser.
Added 'Admin' superuser.
Added 'BlockedUser' as a user that is already blocked when created.

fix #40

### CODE REVIEW

**Comment by danitLevi** [comment]
LGTM

**Comment by avivz450** [comment]
LGTM

**Review by ifireball — CHANGES_REQUESTED** [review]
Do not change existing migration files.

**Review by ifireball — APPROVED** [review]
LGTM

**Pull request merged**
