### PR TITLE
Creating conftest.py

### LINKED ISSUE #114: create conftest.py
file that bind some useful fixtures that can be related to multiple tests classes.

### PR DESCRIPTION
**Pull request by idokk1**
Creating conftest.py and put there useful common pytest fixtures . 
Add create method for Profile model.
move question_test_data() fixture from test_question_tag_model_function.py to conftest.py.
fix #114

### CODE REVIEW

**Comment by ifireball** [comment]
Wan't there a test for that `Profile.create()` method? Seems to be missing....

**Comment by idokk1** [comment]
> Wan't there a test for that `Profile.create()` method? Seems to be missing....

right, added.

**Review by ifireball — APPROVED** [review]
LGTM so far

**Comment by rebeccaTubman** [comment]
Other than the fact that `Profile.create()` method is added twice - in this PR and PR #87, everything looks great.

**Comment by idokk1** [comment]
> Other than the fact that `Profile.create()` method is added twice - in this PR and PR #87, everything looks great.

you right, part of the goals of this PR is to remove some code from #87

**Comment by danitLevi** [comment]
LGTM

**Comment by rebeccaTubman** [comment]
> LGTM

I agree. I think this can be merged.

**Review by avivz450 — APPROVED** [review]

**Comment by liornoy** [comment]
Looks like a helpful addition to the code. thanks

**Review by rebeccaTubman — APPROVED** [review]

**Review by danitLevi — APPROVED** [review]

**Pull request merged**
