### PR TITLE
Adding link to tags page in menu bar

### PR DESCRIPTION
**Pull request by danitLevi**
related to #53

### CODE REVIEW

**Comment by liornoy** [comment]
Maybe remove users link from the navbar also?

**Comment by rebeccaTubman** [comment]
LGTM. Thank you:)

**Comment by liornoy** [comment]
Great fix, maybe delete the Users link? since we said we won't make this page, and you already changing the navbar here.

**Comment by ifireball** [comment]
No description of the change that is intended to be made anywhere - not in the commit messages, not in the PR description and not in the issue.

How am I supposed to understand what kind of change did you intend to do? "Updating menu bar" is a far too generic title.

**Review by ifireball — APPROVED** [review]

**Pull request merged**
