### PR TITLE
Fixed settings.py and urls.py to work for 'home'

### PR DESCRIPTION
**Pull request by rebeccaTubman**
A commit following the last 'Init home app' PR where 'landingpage'
was changed to 'home' but had the files above relate to the previous
name.

modified:   shlifim/settings.py, shlifim/urls.py

### CODE REVIEW

**Comment by liornoy** [comment]
Great fix

**Comment by ifireball** [comment]
I'm seeing the URL from the landing page being removed, but I'm not seeing a URL for the new home app beong added. Where is it?

**Comment by rebeccaTubman** [comment]
I didn't added one because we haven't created a view for home app yet.

**Comment by liornoy** [comment]
> I'm seeing the URL from the landing page being removed, but I'm not seeing a URL for the new home app being added. Where is it?

We will make different PR for it with the needed changes to views and add templates and urls

**Comment by danitLevi** [comment]
> > I'm seeing the URL from the landing page being removed, but I'm not seeing a URL for the new home app being added. Where is it?
> 
> We will make different PR for it with the needed changes to views and add templates and urls

I Agree . I think it's okay if at this point when entering our web the default Django success message will be displayed and we will add our new home page in a separate PR in the future and update the url file .

**Review by ifireball — APPROVED** [review]

**Pull request merged**
