### PR TITLE
Added a Django development environment

### PR DESCRIPTION
**Pull request by rebeccaTubman**
- Bootstrapped an empty [Django][1] application
- Setup Vagrant to automatically bring our application up as well as
  make it accessible from a web browser

After running `vagrant up` the application can be accessed at:

> http://127.0.0.1:8000/

**Note:** Most changes had been auto-generated, only `Vagrantfile`
had been edited manually.

[1]: https://www.djangoproject.com/

### CODE REVIEW

**Comment by ifireball** [comment]
I'm not seeing changes to the Vagrantfile in this PR, did you forget to add them?

**Comment by rebeccaTubman** [comment]
All the changes I should have made in Vagrantfile were already been made by Danit in the first PR.
The file already includes lines:
```
config.vm.network(
"forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
) 
config.vm.provision “shell”, path: “setup.sh”, privileged: false
```
therefore I didn't add it to my PR.

**Comment by ifireball** [comment]
Well, I'm asking becuase you explicitly mentioned the `Vagrantfile` in the Pr description...

**Comment by rebeccaTubman** [comment]
Sorry, I shouldn't have included this note.

**Comment by ifireball** [comment]
I see two commits in this PR, but the commit messages do not explain what each one contain in a way that allows me to understand why they are separate.

**Review by ifireball — APPROVED** [review]
LGTM.

Do you want this merged now? Did other team members have a look? Any additional comments?

**Comment by danitLevi** [comment]
I think you can merge it now .

**Pull request merged**
