### PR TITLE
Adding Question model

### LINKED ISSUE #19: Create Question Model and Migrations
Create a DB table for questions following the table in the ERD which includes:
* question id(PK)
* user id(FK)
* title
* content
* publish date
* subject id(FK)
* grade
* sub subject id (FK)
 * book id (FK)
* book page 
* is edited

### PR DESCRIPTION
**Pull request by danitLevi**
- Updating modles.py file:
	* add Grade class which contain grade choices (Seventh Grade until Twelfth grade) 
	* add Question class based on the ERD 
- Updating admin.py file in order to view questions data in admin page
- update migrations files

fix #19 
related to #27

*  I also included the code from the unmerged PR Lior opened (#24 ) because I needed  subject, sub-subject and book models

### CODE REVIEW

**Comment by liornoy** [comment]
It looks great.
Maybe add some more questions to the test_data so the initial database will be fuller,
and so we will have content to play with when designing the views later.

Preferably the questions will include different authors and different publish dates,
with/without books etc.
Also in home/migrations/0002_test_data.py. Looking at: 
```
for username, title, content, publish_date, subject_id, sub_subject_id, \
grade, book_id, book_page, is_edited in question_test_data: 
```

I think the question_test_data list items will be more readable if you used the object's name instead of id. this way instead of: 
```
('Danit', 'question from math course', 'Hey , Can someome help me solve the equation 1+1',
             timezone.now(), 9, 1, '7', 1, 10, True),
```

You'll have something like:
 ```

('Danit', 'question from math course', 'Hey , Can someome help me solve the equation 1+1',
             timezone.now(), 'Math', 'Algebra', '7', 'Yoel Geva', 10, True),
 ```

**Comment by idokk1** [comment]
image
Hi , 
I think maybe in you __str__ function you should return on the content and ID. The date is looks bad when I show it in the admin page.

**Comment by idokk1** [comment]
maybe change the str function to : 
```
 def __str__(self):
        return f"Question #{self.id} : {self.title} ( {self.publish_date.strftime('%d/%m/%Y %H:%M')} )"
```
and then it will look like this : 
image

**Comment by danitLevi** [comment]
@idokk1 
I updated admin.py file and added "QuestionAdmin" class , so in the admin page the question Shown in a table with the following columns: id, title , publish date , subject, and not the as presented In the str function. 
(I followed Lior's suggestion in issue #27 ) .
It worked fine for me. Maybe you forgot to update admin.py file?
In addition , Let me know if you want me to change something in QuestionAdmin class .

**Comment by idokk1** [comment]
I use the str function when I want to show the question as a column in the Answer admin page: 
image

**Comment by liornoy** [comment]
> Good idea @liornoy .
> I will add some more questions to the test_data.
> 
> In addition , I thought we wanted to map objects by id.
> I can change it, but if we will map objects by their names we should also change the Subject, Sub-subject, and Book models and convert their name fields into unique fields ( using unique=True )

I changed my PR as you suggested. thank you

**Comment by danitLevi** [comment]
I will change it as you suggested thank you .

**Comment by danitLevi** [comment]
> maybe change the str function to :
> 
> ```
>  def __str__(self):
>         return f"Question #{self.id} : {self.title} ( {self.publish_date.strftime('%d/%m/%Y %H:%M')} )"
> ```
> 
> and then it will look like this :
> image

I will change it as you suggested thank you @idokk1  .

**Comment by danitLevi** [comment]
@liornoy @idokk1 
I did the required changes. 
Let me know if you want me to do more changes.

**Comment by idokk1** [comment]
LGTM

**Review by ifireball — CHANGES_REQUESTED** [review]
Merged migrations files should not be modifoed, instead, new files must be atted.
Since all of you are introducing models into the same Django app, all the model modification MRs conflict with one another and more be based on each other.

**Comment by ifireball** [comment]
Please resolve the merge conflict - one possible reason for it is that this MR is attempting to change the 002 migration file (as always, migration files shouldn't be changed once they are merged)

**Comment by danitLevi** [comment]
> Please resolve the merge conflict - one possible reason for it is that this MR is attempting to change the 002 migration file (as always, migration files shouldn't be changed once they are merged)

@ifireball Done

**Review by ifireball — APPROVED** [review]

**Pull request merged**
