### PR TITLE
Create home app base

### LINKED ISSUE #12: Create base.html file
The base.html file will be inherited by all the other HTML files and will include
a Navbar with links to other pages, a search box for questions, and authentication buttons (Login/Logout and profile page).
Moreover, the base.html will have all the needed CSS links and messages logic for showing one-time messages to the user
(for example confirmation for creating a user or posting a question).

### PR DESCRIPTION
**Pull request by liornoy**
fix #12 and #11

### CODE REVIEW

**Review by ifireball — APPROVED** [review]
LGTM

**Comment by danitLevi** [comment]
I think it can be merged

**Comment by liornoy** [comment]
I noticed bugs in the base.html file. Please don't merge yet

**Comment by ifireball** [comment]
Can this be merged now?

**Comment by liornoy** [comment]
> Can this be merged now?

Yes imo

**Pull request merged**
